name: Go build and test

on:
  push:
    branches: [ "main" ]

permissions:
    contents: write
    packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -o vault cmd/main.go
